services:
  # Сервис для Telegram бота
  - type: web
    name: telegram-bot-service
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: python render_app.py
    plan: free
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false # Этот параметр нужно будет установить вручную в Render
      - key: DATABASE_URL
        fromDatabase:
          name: bot-database
          property: connectionString
      - key: RENDER
        value: "true" # Указывает, что бот запущен в среде Render

# База данных для бота
databases:
  - name: bot-database
    plan: free
    databaseName: bot_db