services:
  # Сервис для Telegram бота
  - type: web
    name: telegram-bot-service
    env: python
    buildCommand: pip install -r render_requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false # Этот параметр нужно будет установить вручную в Render
      - key: DATABASE_URL
        fromDatabase:
          name: bot-database
          property: connectionString
      - key: PORT
        value: 10000 # Порт можно изменить на любой другой, если необходимо

# База данных для бота
databases:
  - name: bot-database
    plan: free
    databaseName: bot_db